version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/app
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/stock-genius
